force-app/main/default/objects/Management__c/Management__c.object-meta.xml
<CustomObject>
    <label>事故受付・伝言管理</label>
    <nameField>
        <label>受付番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Management__c/fields/ContractorName__c.field-meta.xml
<CustomField>
    <fullName>ContractorName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>コールデータ情報</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>事故受付・伝言管理</relationshipLabel>
    <relationshipName>Contact_Manegement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateManagementController.cls
public with sharing class CreateManagementController {
    
    public CreateManagementController() {   }
    
    @AuraEnabled
    public static string managementCase(Id managementRecordTypeId, Id accidentRecordId) {
        // Create new Management        
        Management__c managementObj = new Management__c();
        
        // レコードタイプを設定
        managementObj.RecordTypeId = managementRecordTypeId;
        if(string.isNotBlank(accidentRecordId)){
            managementObj.ContractorName__c = accidentRecordId;
        }
        
        insert managementObj;
        return managementObj.id;        
    }
}