force-app/main/default/objects/Contact/fields/AccidentDate__c.field-meta.xml
<CustomField>
    <fullName>AccidentDate__c</fullName>
    <label>事故日</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CallerContactInformation1__c.field-meta.xml
<CustomField>
    <fullName>CallerContactInformation1__c</fullName>
    <label>入電者の連絡先</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CallerContactInformation2__c.field-meta.xml
<CustomField>
    <fullName>CallerContactInformation2__c</fullName>
    <label>入電者の連絡先２</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ContractorName__c.field-meta.xml
<CustomField>
    <fullName>ContractorName__c</fullName>
    <label>契約者名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IncomingCallDay__c.field-meta.xml
<CustomField>
    <fullName>IncomingCallDay__c</fullName>
    <label>第一報入電日</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IncomingCallTime__c.field-meta.xml
<CustomField>
    <fullName>IncomingCallTime__c</fullName>
    <label>第一報入電時間</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>証券番号</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RegisteredPhoneNumber1__c.field-meta.xml
<CustomField>
    <fullName>RegisteredPhoneNumber1__c</fullName>
    <label>登録の電話番号</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RegisteredPhoneNumber2__c.field-meta.xml
<CustomField>
    <fullName>RegisteredPhoneNumber2__c</fullName>
    <label>登録の電話番号２</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>入電者と契約者の関係</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/Management__c.object-meta.xml
<CustomObject>
    <label>事故受付・伝言管理</label>
    <nameField>
        <label>受付番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Management__c/fields/AccidentDate__c.field-meta.xml
<CustomField>
    <fullName>AccidentDate__c</fullName>
    <label>事故日</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>事故の事故日に同じ</fullName>
            </value>
            <value>
                <fullName>フリー入力</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Management__c/fields/AccidentSituation__c.field-meta.xml
<CustomField>
    <fullName>AccidentSituation__c</fullName>
    <label>事故状況・原因</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/AccidentTime__c.field-meta.xml
<CustomField>
    <fullName>AccidentTime__c</fullName>
    <description>※傷害・傷害以外のみ反映</description>
    <label>事故時間</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/Agency1__c.field-meta.xml
<CustomField>
    <fullName>Agency1__c</fullName>
    <label>代理店①</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/Agency2__c.field-meta.xml
<CustomField>
    <fullName>Agency2__c</fullName>
    <label>代理店②</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/BillingAddressInput__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressInput__c</fullName>
    <label>送付先住所と宛名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/CallDate__c.field-meta.xml
<CustomField>
    <fullName>CallDate__c</fullName>
    <label>入電日</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/CallerContactInfo__c.field-meta.xml
<CustomField>
    <fullName>CallerContactInfo__c</fullName>
    <label>連絡先</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/CallerContractorRelationInput__c.field-meta.xml
<CustomField>
    <fullName>CallerContractorRelationInput__c</fullName>
    <label>入電者の続柄</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/CallerNameInput__c.field-meta.xml
<CustomField>
    <fullName>CallerNameInput__c</fullName>
    <label>入電者（氏名）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/ContactAddressInput__c.field-meta.xml
<CustomField>
    <fullName>ContactAddressInput__c</fullName>
    <label>宛名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/ContactPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>ContactPhoneNumber__c</fullName>
    <label>電話番号</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/ContractorName__c.field-meta.xml
<CustomField>
    <fullName>ContractorName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>コールデータ情報</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>事故受付・伝言管理</relationshipLabel>
    <relationshipName>Contact_Manegement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/ContractorNameInput1__c.field-meta.xml
<CustomField>
    <fullName>ContractorNameInput1__c</fullName>
    <label>契約者名①</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/ContractorNameInput2__c.field-meta.xml
<CustomField>
    <fullName>ContractorNameInput2__c</fullName>
    <label>契約者名②</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/CurrentSituationInput__c.field-meta.xml
<CustomField>
    <fullName>CurrentSituationInput__c</fullName>
    <label>現在の状況</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/Damaged__c.field-meta.xml
<CustomField>
    <fullName>Damaged__c</fullName>
    <label>損害物</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/DepartmentNameInput1__c.field-meta.xml
<CustomField>
    <fullName>DepartmentNameInput1__c</fullName>
    <label>①（選択不可の場合）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/DepartmentNameInput2__c.field-meta.xml
<CustomField>
    <fullName>DepartmentNameInput2__c</fullName>
    <label>②（選択不可の場合）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/DestinationLocation__c.field-meta.xml
<CustomField>
    <fullName>DestinationLocation__c</fullName>
    <label>被害物件住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/HospitalName__c.field-meta.xml
<CustomField>
    <fullName>HospitalName__c</fullName>
    <label>病院名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/HospitalTel__c.field-meta.xml
<CustomField>
    <fullName>HospitalTel__c</fullName>
    <label>病院TEL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InconvenientTime__c.field-meta.xml
<CustomField>
    <fullName>InconvenientTime__c</fullName>
    <label>時間指定</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsuranceItem1__c.field-meta.xml
<CustomField>
    <fullName>InsuranceItem1__c</fullName>
    <label>保険種目①</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsuranceItem2__c.field-meta.xml
<CustomField>
    <fullName>InsuranceItem2__c</fullName>
    <label>保険種目②</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsurancePeriod1From__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriod1From__c</fullName>
    <label>保険始期日①</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsurancePeriod1To__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriod1To__c</fullName>
    <label>保険終期日①</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsurancePeriod2From__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriod2From__c</fullName>
    <label>保険始期日②</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsuredAddress__c.field-meta.xml
<CustomField>
    <fullName>InsuredAddress__c</fullName>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsuredContactInfoInput__c.field-meta.xml
<CustomField>
    <fullName>InsuredContactInfoInput__c</fullName>
    <label>連絡先Ａ</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsuredContactInput2__c.field-meta.xml
<CustomField>
    <fullName>InsuredContactInput2__c</fullName>
    <label>連絡先Ｂ</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsuredKana__c.field-meta.xml
<CustomField>
    <fullName>InsuredKana__c</fullName>
    <label>被保険者名（カナ）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsuredNameInput__c.field-meta.xml
<CustomField>
    <fullName>InsuredNameInput__c</fullName>
    <label>被保険者名（漢字）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsuredPersonInput1__c.field-meta.xml
<CustomField>
    <fullName>InsuredPersonInput1__c</fullName>
    <label>記名被保険者名①</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/InsuredPersonInput2__c.field-meta.xml
<CustomField>
    <fullName>InsuredPersonInput2__c</fullName>
    <label>記名被保険者名②</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/LocationTypeSupplement__c.field-meta.xml
<CustomField>
    <fullName>LocationTypeSupplement__c</fullName>
    <label>場所種別（補足）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/OtherPartyAddress__c.field-meta.xml
<CustomField>
    <fullName>OtherPartyAddress__c</fullName>
    <label>住所（相手情報）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/OtherPartyContactInfoA__c.field-meta.xml
<CustomField>
    <fullName>OtherPartyContactInfoA__c</fullName>
    <label>連絡先A</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/OtherPartyContactInfoB__c.field-meta.xml
<CustomField>
    <fullName>OtherPartyContactInfoB__c</fullName>
    <label>連絡先B</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/OtherPartyKana__c.field-meta.xml
<CustomField>
    <fullName>OtherPartyKana__c</fullName>
    <label>相手氏名（カナ）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/OtherPartyName__c.field-meta.xml
<CustomField>
    <fullName>OtherPartyName__c</fullName>
    <label>相手氏名（漢字）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <label>部位</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/PersonInfoConfirm__c.field-meta.xml
<CustomField>
    <fullName>PersonInfoConfirm__c</fullName>
    <label>確認有無</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>案内のうえ了承済み</fullName>
            </value>
            <value>
                <fullName>未</fullName>
                <isActive>false</isActive>
                <label>未</label>
            </value>
            <value>
                <fullName>済</fullName>
                <isActive>false</isActive>
                <label>済</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Management__c/fields/PersonInfoConfirmInput__c.field-meta.xml
<CustomField>
    <fullName>PersonInfoConfirmInput__c</fullName>
    <label>同意者</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/RemarksInsurance__c.field-meta.xml
<CustomField>
    <fullName>RemarksInsurance__c</fullName>
    <label>備考</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/RemarksReason__c.field-meta.xml
<CustomField>
    <fullName>RemarksReason__c</fullName>
    <label>備考</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/SecuritiesBranchNumber1__c.field-meta.xml
<CustomField>
    <fullName>SecuritiesBranchNumber1__c</fullName>
    <label>枝番①</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/SecuritiesBranchNumber2__c.field-meta.xml
<CustomField>
    <fullName>SecuritiesBranchNumber2__c</fullName>
    <label>枝番②</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/Supplement__c.field-meta.xml
<CustomField>
    <fullName>Supplement__c</fullName>
    <label>補記</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Management__c/fields/Symptoms__c.field-meta.xml
<CustomField>
    <fullName>Symptoms__c</fullName>
    <label>症状</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ManagementTriggerTest.cls
@isTest
private class ManagementTriggerTest {
    public static Management__c app;

    @isTest static void updateTest1(){
       
        // test start
        try{
            
            Contact contact = new Contact(MobilePhone = '03-1234-5678' ,
                                          LastName = 'トランス', FirstName = '',
                                          ContractorName__c='aa', AccidentDate__c = 'R3/1/1',
                                          PolicyNumber__c='266262-111', IncomingCallTime__c = '22:22',
                                          IncomingCallDay__c = 'R2/12/11', RegisteredPhoneNumber1__c = '151551',
                                          Relationship__c = 'aa', CallerContactInformation1__c = '111',
                                          RegisteredPhoneNumber2__c = '111',
                                          CallerContactInformation2__c = '22') ;
            insert contact;
            
            List<InputCheck__c> inputChk = new List<InputCheck__c>();
            InputCheck__c inputChkobj = new InputCheck__c(
                						Name = '契約者名①' ,
                                        InputItemAPIName__c = 'ContractorNameInput1__c',
                                        Size__c=13) ;
            insert inputChkobj;
            
            List<Management__c> managements = new List<Management__c>();
            Management__c app = new Management__c(   
                ContractorName__c = contact.id,
                CallerContactInfo__c = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                CallerNameInput__c = 'aaaaaaaaaaaaaaaaaaaa',
                CallerContractorRelationInput__c = 'aaaaaaaaaaaaaaaaaaaa',
                SecuritiesBranchNumber1__c = 'aaaaaaaaaaaaaaaaaaaa',
                SecuritiesBranchNumber2__c = 'aaaaaaaaaaaaaaaaaaaa',
                ContractorNameInput1__c = 'aaaaaaaaaaaaaaaaaaaa',
                ContractorNameInput2__c = 'aaaaaaaaaaaaaaaaaaaa',
                InsuredPersonInput1__c = 'aaaaaaaaaaaaaaaaaaaa',
                InsuredPersonInput2__c = 'aaaaaaaaaaaaaaaaaaaa',
                Agency1__c = 'aaaaaaaaaaaaaaaaaaaa',
                Agency2__c = 'aaaaaaaaaaaaaaaaaaaa',
                InsuranceItem1__c = 'aaaaaaaaaaaaaaaaaaaa',
                InsuranceItem2__c = 'aaaaaaaaaaaaaaaaaaaa',
                DisasterName__c = 'aaaaaaaaaaaaaaaaaaaa',
                AccidentSituation__c = 'aaaaaaaaaaaaaaaaaaaa',
                InsuredKana__c = 'aaaaaaaaaaaaaaaaaaaa',
                InsuredNameInput__c = 'aaaaaaaaaaaaaaaaaaaa',
                InsuredAddress__c = 'aaaaaaaaaaaaaaaaaaaa',
                InsuredContactInfoInput__c = 'aaaaaaaaaaaaaaaaaaaa',
                InsuredContactInput2__c = 'aaaaaaaaaaaaaaaaaaaa',
                DestinationLocation__c = 'aaaaaaaaaaaaaaaaaaaa',
                OtherPartyKana__c = 'aaaaaaaaaaaaaaaaaaaa',
                OtherPartyName__c = 'aaaaaaaaaaaaaaaaaaaa',
                OtherPartyAddress__c = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                OtherPartyContactInfoA__c = 'aaaaaaaaaaaaaaaaaaaa',
                OtherPartyContactInfoB__c = 'aaaaaaaaaaaaaaaaaaaa',
                Damaged__c = 'aaaaaaaaaaaaaaaaaaaa',
                Part__c = 'aaaaaaaaaaaaaaaaaaaa',
                Symptoms__c = 'aaaaaaaaaaaaaaaaaaaa',
                HospitalName__c = 'aaaaaaaaaaaaaaaaaaaa',
                HospitalTel__c = 'aaaaaaaaaaaaaaaaaaaa',
                LocationTypeSupplement__c = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                
                CurrentSituationInput__c = 'aaaaaaaaaaaaaaaaaaaa',
                RemarksInsurance__c = 'aaaaaaaaaaaaaaaaaaaa',
                RemarksReason__c = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                PersonInfoConfirmInput__c = 'aaaaaaaaaaaaaaaaaaaa',
                BillingAddressInput__c = 'aaaaaaaaaaaaaaaaaaaa',
                ContactAddressInput__c = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                ContactPhoneNumber__c = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                InconvenientTime__c = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                PersonInfoConfirm__c = '案内のうえ了承済み',
                
                Remarks__c = 'aaaaaaaaaaaaaaaaaaaa',
                Supplement__c = 'aaaaaaaaaaaaaaaaaaaa',
                DepartmentNameInput1__c = 'aaaaaaaaaaaaaaaaaaaa',
                DepartmentNameInput2__c = 'aaaaaaaaaaaaaaaaaaaa',
                AccidentTime__c = 'aaaaaaaaaaaaaaaaaaaa',
                CallDate__c = 'R3/1/1',
                InsurancePeriod1From__c = 'R 21.10. 1',
                InsurancePeriod2From__c = 'H 21.10. 1',
                InsurancePeriod1To__c = 'S 21.10. 1',
                InsurancePeriod2To__c = 'M 21.10. 1',
                AccidentDateInputW__c = 'R2/12/3',
                InsuredPersonBirthW__c = 'S3/1/1',
                OtherPartyBirthW__c = 'S21/1/1',
                
                ExpectedHospitalFrom__c = 'S21/1/1',
                ExpectedHospitalTo__c = 'S21/1/1',
                ExpectedHospitalizationFrom__c = 'S21/1/1',
                ExpectedHospitalizationTo__c = 'S21/1/1',
                CastFixedPeriodFrom__c = 'S21/1/1',
                CastFixedPeriodTo__c = 'S21/1/1',
                ContactDateW__c = 'S21/1/1',
                
                CallDataIncomingCallTime__c = '12:11',                
                InsuredZipCode__c = 'X0044',
                SecuritiesNumberInput1__c = 'M',
                SecuritiesNumberInput2__c = 'M',
                
                
                DriverBirthInputW__c = 'S21/1/1',
                EntrustContractDate__c = 'S21/1/1',
                DeliveryDate__c = 'S21/1/1',
                InjuredBirthday__c = 'S21/1/1',
                InjuredBirthdayCL__c = 'S21/1/1',
                
                
                EntrustContractTime__c = '12:12',
                DeliveryTime__c = '::',
                
                SecuritiesNumbeYot__c = '/',                
                EntrusterPhoneNumber__c = '/'
                
            );
            
            //insert 
            Test.startTest();
			insert app;
            Test.stopTest();
            
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
    
    @isTest static void updateTest2(){
        // test start
        try{
            
            Contact contact = new Contact(MobilePhone = '03-1234-5678' ,
                                          LastName = 'トランス', FirstName = '',
                                          ContractorName__c='aa', AccidentDate__c = 'R3/1/1',
                                          PolicyNumber__c='266262-111', IncomingCallTime__c = '22:22',
                                          IncomingCallDay__c = 'R2/12/0', RegisteredPhoneNumber1__c = '151551',
                                          Relationship__c = 'aa', CallerContactInformation1__c = '111',
                                          CallerContactInformation2__c = '22') ;
            insert contact;        
            List<Management__c> managements = new List<Management__c>();
            Management__c app = new Management__c(   
                ContractorName__c = contact.id,
                CallDate__c = 'R3/1/0',
                InsurancePeriod1From__c = 'R 21.10. 0',
                InsurancePeriod2From__c = 'H 21.10. 0',
                InsurancePeriod1To__c = 'S 21.10. 0',
                InsurancePeriod2To__c = 'M 21.10. 0',
                AccidentDateInputW__c = 'R3/2/1',
                InsuredPersonBirthW__c = 'S3/1/0',
                OtherPartyBirthW__c = 'S21/1/0',
                
                ExpectedHospitalFrom__c = 'R3/1/0',
                ExpectedHospitalTo__c = 'H3/1/0',
                ExpectedHospitalizationFrom__c = 'S3/1/0',
                ExpectedHospitalizationTo__c = 'M3/1/0',
                CastFixedPeriodFrom__c = 'R3/1/0',
                CastFixedPeriodTo__c = 'R3/1/0',
                ContactDateW__c = 'R3/1/0',
                
                CallDataIncomingCallTime__c = '12:',                
                InsuredZipCode__c = 'X0044',
                SecuritiesNumberInput1__c = 'R3/1/0',
                SecuritiesNumberInput2__c = 'R3/1/0',
                
                
                DriverBirthInputW__c = 'R3/1/0',
                EntrustContractDate__c = 'R3/1/0',
                DeliveryDate__c = 'R3/1/0',
                InjuredBirthday__c = 'R3/1/0',
                InjuredBirthdayCL__c = 'R3/1/0',
                
                
                EntrustContractTime__c = '12:',
                DeliveryTime__c = '12:12',
                
                SecuritiesNumbeYot__c = '123456',                
                EntrusterPhoneNumber__c = '123456',
                
                Phase__c = 'SV承認待ち'
                
                
                
                
            );
            
            insert app;   
            
            test.startTest();
            app.PersonInfoConfirm__c = '案内のうえ了承済み';
            //app.Phase__c = 'SV承認待ち';
            update app;
            
            test.stopTest();
            
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
    @isTest static void updateTest3(){
        // test start
        try{
            
            Contact contact = new Contact(MobilePhone = '03-1234-5678' ,
                                          LastName = 'トランス', FirstName = '',
                                          ContractorName__c='', AccidentDate__c = '',
                                          PolicyNumber__c='', IncomingCallTime__c = '',
                                          IncomingCallDay__c = 'aaa', RegisteredPhoneNumber1__c = '',
                                          Relationship__c = '', CallerContactInformation1__c = '',
                                          CallerContactInformation2__c = '') ;
            insert contact;        
            List<Management__c> managements = new List<Management__c>();
            Management__c app = new Management__c(   
                ContractorName__c = contact.id,
                CallDate__c = 'aaa',
                InsurancePeriod1From__c = 'aaa',
                InsurancePeriod2From__c = 'aaaa',
                InsurancePeriod1To__c = 'aaaa',
                InsurancePeriod2To__c = 'aaaaa',
                AccidentDateInputW__c = 'aaaaa',
                InsuredPersonBirthW__c = 'SS',
                OtherPartyBirthW__c = 'aaaaa',
                ExpectedHospitalFrom__c = 'aaaaa',
                ExpectedHospitalTo__c = 'aaaaa',
                ExpectedHospitalizationFrom__c = 'aaaaa',
                ExpectedHospitalizationTo__c = 'aaaaa',
                CastFixedPeriodFrom__c = 'aaaaa',
                CastFixedPeriodTo__c = 'aaaaa',
                ContactDateW__c = 'aaaaa',
                CallDataIncomingCallTime__c = '12:',                
                InsuredZipCode__c = 'X0044',
                SecuritiesNumberInput1__c = 'aaaaa',
                SecuritiesNumberInput2__c = 'aaaaa',
                DriverBirthInputW__c = 'aaaaa',
                EntrustContractDate__c = 'aaaaa',
                DeliveryDate__c = 'aaaaa',
                InjuredBirthday__c = 'aaaaa',
                InjuredBirthdayCL__c = 'aaaaa',
                EntrustContractTime__c = '12:',
                DeliveryTime__c = '12:12',
                SecuritiesNumbeYot__c = '123456',                
                EntrusterPhoneNumber__c = '123456',
                AccidentTimeNisei__c = 'aaaaa',
                SecuritiesBranchNumber1__c = 'ああああ',
                SecuritiesBranchNumber2__c = 'あああ',
                Phase__c = '対応中'
            );
            
            insert app;   
            
            test.startTest();
            
            update app;
            
            test.stopTest();
            
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
    @isTest static void updateTestInsurance(){
        // test start
        try{
            
            Contact contact = new Contact(MobilePhone = '03-1234-5678' ,
                                          LastName = 'トランス', FirstName = '',
                                          ContractorName__c='', AccidentDate__c = '',
                                          PolicyNumber__c='', IncomingCallTime__c = '',
                                          IncomingCallDay__c = '', RegisteredPhoneNumber1__c = '',
                                          Relationship__c = '', CallerContactInformation1__c = '',
                                          CallerContactInformation2__c = '') ;
            insert contact;        
            List<Management__c> managements = new List<Management__c>();
            Management__c app = new Management__c(   
                ContractorName__c = contact.id,
                InsurancePeriod1From__c = 'R/2/1',
                InsurancePeriod2From__c = 'H/2/1',
                InsurancePeriod1To__c = 'S/12/1',
                InsurancePeriod2To__c = 'T/12/2'

            );
            
            insert app;   
            
            test.startTest();
            
            update app;
            
            test.stopTest();
            
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
    
    @isTest static void updateTestInsurance2(){
        // test start
        try{
            
            Contact contact = new Contact(MobilePhone = '03-1234-5678' ,
                                          LastName = 'トランス', FirstName = '',
                                          ContractorName__c='', AccidentDate__c = '',
                                          PolicyNumber__c='', IncomingCallTime__c = '',
                                          IncomingCallDay__c = 'H2/12/11', RegisteredPhoneNumber1__c = '',
                                          Relationship__c = '', CallerContactInformation1__c = '',
                                          CallerContactInformation2__c = '') ;
            insert contact;        
            List<Management__c> managements = new List<Management__c>();
            Management__c app = new Management__c(   
                ContractorName__c = contact.id,
                InsurancePeriod1From__c = 'R3/2/0',
                InsurancePeriod2From__c = 'H3/2/0',
                InsurancePeriod1To__c = 'S3/12/0',
                InsurancePeriod2To__c = 'T3/12/0'

            );
            
            insert app;   
            
            test.startTest();
            
            update app;
            
            test.stopTest();
            
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
    
    @isTest static void updateTestDateNull(){
        // test start
        try{
            
            Contact contact = new Contact(MobilePhone = '03-1234-5678' ,
                                          LastName = 'トランス', FirstName = '',
                                          ContractorName__c='', AccidentDate__c = '',
                                          PolicyNumber__c='', IncomingCallTime__c = '',
                                          IncomingCallDay__c = 'H2/12/11', RegisteredPhoneNumber1__c = '',
                                          Relationship__c = '', CallerContactInformation1__c = '',
                                          CallerContactInformation2__c = '') ;
            insert contact;        
            List<Management__c> managements = new List<Management__c>();
            Management__c app = new Management__c(   
                ContractorName__c = contact.id,
                InsurancePeriod1From__c = '',
                InsurancePeriod2From__c = '',
                InsurancePeriod1To__c = '',
                InsurancePeriod2To__c = ''

            );
            
            insert app;   
            
            test.startTest();
            
            update app;
            
            test.stopTest();
            
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
    
    @isTest static void updateTest4(){
        // test start
        try{
            
            Contact contact = new Contact(MobilePhone = '03-1234-5678' ,
                                          LastName = 'トランス', FirstName = '',
                                          ContractorName__c='', AccidentDate__c = '',
                                          PolicyNumber__c='', IncomingCallTime__c = '',
                                          IncomingCallDay__c = 'H2/12/11', RegisteredPhoneNumber1__c = '',
                                          Relationship__c = '', CallerContactInformation1__c = '',
                                          CallerContactInformation2__c = '') ;
            insert contact;        
            List<Management__c> managements = new List<Management__c>();
            Management__c app = new Management__c(   
                ContractorName__c = contact.id,
                CallerContactInfo__c = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                Phase__c = 'SV確認中',
                PersonInfoConfirm__c ='案内のうえ了承済み',
                InsurancePeriod1From__c = 'R3/1/2',
                InsurancePeriod2From__c = 'S3/1/2',
                InsurancePeriod1To__c = 'H3/1/2',
                InsurancePeriod2To__c = 'T3/1/2'
            );
            
            insert app;   
            
            test.startTest();
            
            update app;
            
            test.stopTest();
            
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
    @isTest static void insertAnnoymousContact(){
        
        // test start
        try{
            
            Contact contact = new Contact(MobilePhone = '03-1234-5678' ,
                                          ContractorName__c='aa', AccidentDate__c = 'R3/1/1',
                                          PolicyNumber__c='266262-111', IncomingCallTime__c = '22:22',
                                          IncomingCallDay__c = 'R2/12/11', RegisteredPhoneNumber1__c = '151551',
                                          Relationship__c = 'aa', CallerContactInformation1__c = '111',
                                          RegisteredPhoneNumber2__c = '111',
                                          CallerContactInformation2__c = '22',
                                          BedoreSessionID__c = '123456'
                                         ) ;    
            insert contact;
            system.assertEquals(1, [select id from contact].size());
            system.assertEquals('フメイ', [select id, LastName from contact].get(0).LastName);
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
}